[package]
name = "binance"
version = "0.10.7"
license = "MIT OR Apache-2.0"
authors = ["Flavio Oliveira <flavio@wisespace.io>"]
edition = "2018"

description = "Rust Library for the Binance API"
keywords = ["cryptocurrency", "trading", "binance"]
categories = ["api-bindings", "cryptography::cryptocurrencies"]
documentation = "https://docs.rs/crate/binance/"
repository = "https://github.com/wisespace-io/binance-rs"
readme = "README.md"

[badges]
travis-ci = { repository = "wisespace-io/binance-rs" }

[lib]
name = "binance"
path = "src/lib.rs"

[dependencies]
hex = "0.4"
hmac = "0.9"
sha2 = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
error-chain = { version = "0.12", default-features = false }
reqwest = { version = "0.10", features = ["blocking", "json"] }
tungstenite = "0.11.1"
url = "2.1"

[features]
vendored-tls = ["reqwest/native-tls-vendored", "tungstenite/tls-vendored"]

[dev-dependencies]
csv = "1.0.0"
