[package]
name = "binance"
version = "0.1.1"
license = "MIT OR Apache-2.0"
authors = ["Flavio Oliveira <flavio@wisespace.io>"]

description = "Rust Library for the Binance API"
keywords = ["cryptocurrency", "trading"]
repository = "https://github.com/wisespace-io/binance-rs"
readme = "README.md"

[badges]
travis-ci = { repository = "wisespace-io/binance-rs" }

[lib]
name = "binance"
path = "src/lib.rs"

[dependencies]
log = "0.3.8"
hex = "0.2"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
error-chain = "0.11.0"
ring = "0.12.1"
reqwest = "0.8.0"
tokio-core = "0.1.10"
futures = "0.1.17"
tokio-tungstenite = "0.4.0"
tungstenite = "0.5.0"
url = "1.6.0"